spring:
  profiles:
    active: t01
  datasource:
    url: jdbc:postgresql://localhost:5432/contactdb_t01
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082
